#Docker version 27.3.1, build ce12230
services:

  db:
    image: postgres:15.2
    container_name: idm-database-container
    restart: always
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=idm
      - POSTGRES_USER=jhonny
      - POSTGRES_PASSWORD=berdeja
    ports:
      - "5434:5432"
  mongodb:
    image: mongo:6.0
    container_name: container_database_mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: db-mongodb-jberdeja
      MONGO_INITDB_ROOT_USERNAME: jhonny
      MONGO_INITDB_ROOT_PASSWORD: clavejhonny
    ports:
      - "27017:27017"
    volumes:
      - ./JSON-like/init.js:/docker-entrypoint-initdb.d/init.js
